### PR TITLE
Restructure project and fix all issues

### LINKED ISSUE #1: I does not work right away
I installed the workflow but didn't manage it to work. Is there some setup routine required?

SourceTree v.2.3.2

### PR DESCRIPTION
**Pull request by mdeboer**
I restructured the project and removed unnecessary files. Also fixed all open issues 👍 

Fixed #1 and #3, also implemented #2.

### CODE REVIEW

**Comment by mdeboer** [comment]
Also, I think it's better to leave the workflow file out of the repository to prevent pushing a new release and forgetting to update the file. Just create a release here on GitHub and attach the workflow file to that release. That way people can still download it if they can't find it on packal.

[SourceTree.alfredworkflow.zip](https://github.com/yourtion/Alfred_SourceTree/files/741048/SourceTree.alfredworkflow.zip)

**Comment by klaas** [comment]
Great improvements! This should be integrated right now!

**Comment by fleXible** [comment]
I disagree regarding the workflow file. Having it in the repository makes it easy for many people to use the workflow, just by downloading and single-click importing it. Personally I wouldn't know how to create a alfredworkflow file from a github repository.

**Comment by mdeboer** [comment]
@fleXible you don't need to as you can include the alfredworkflow file on the [releases](https://github.com/yourtion/Alfred_SourceTree/releases) page. See [alfred-atom](https://github.com/Cloudstek/alfred-atom/releases) for example 👍 

To sum it up:
* Still an easy download (from the releases page)
* Uncluttered repo containing only source files
* Not accidentally committing an outdated alfredworkflow file

**Comment by yourtion** [comment]
@mdeboer Sorry, I didn't see this Pull requests until now. I will merge and publish a new version. thanks  👍   !!

**Pull request merged**
